name: philos

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-project:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update & Installing valgrind
        run: |
          sudo apt update 
          sudo apt install -y valgrind

      - name: Compile
        run: make

      - name: Run 1 philos eat 4 times
        continue-on-error: true
        run: ./philo 1 610 200 200 4

      - name: Run 2 philos eat 4 times
        continue-on-error: true
        run: ./philo 2 410 200 200 4

      - name: Run 4 philos eat 4 times
        continue-on-error: true
        run: ./philo 4 410 200 200 4

      - name: Run 5 philos eat 4 times
        continue-on-error: true
        run: ./philo 5 610 200 200 4

      - name: Run 9 philos eat 4 times
        continue-on-error: true
        run: ./philo 9 35 10 10 4

      - name: Run 200 philos eat 4 times
        continue-on-error: true
        run: ./philo 200 410 200 200 4

      - name: Valgrind (testing Allocation with Race Data)
        continue-on-error: true
        run: valgrind --tool=helgrind ./philo 2 410 200 200 4

      - name: Valgrind (testing Allocation with Race Data)
        continue-on-error: true
        run: valgrind --tool=helgrind ./philo 200 410 200 200 4

  release-project:
      name: Release project
      runs-on: ubuntu-latest
      needs: build-project
      steps:
        - name: Create github release
          id: create-release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.ref_name }}
            release_name: Release ${{ github.ref_name }}
