name: philos

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Update & Installing valgrind
        run: |
          sudo apt update 
          sudo apt install -y valgrind

      - name: Compile
        run: make

      - name: Run 2 philos eat 4 times
        run: ./philo 2 410 200 200 4

      - name: Run 200 philos eat 4 times
        run: ./philo 200 410 200 200 4

      - name: Valgrind (testing Allocation with Race Data)
        run: valgrind --tool=helgrind ./philo 2 410 200 200 4

      - name: Valgrind (testing Allocation with Race Data)
        run: valgrind --tool=helgrind ./philo 200 410 200 200 4
